// chatbot-angular-library/projects/chatbot-angular/src/lib/components/message-bubble/message-bubble.component.ts
import { Component, ChangeDetectionStrategy, input, computed } from '@angular/core';
import { Message } from '../../types';
import { getMessageText, isImageLikePart, isFilePart } from '../../utils/message-parts';
import { StreamingCursorComponent } from '../streaming-cursor/streaming-cursor.component';
import { MarkdownMessageComponent } from '../markdown-message/markdown-message.component';
import { MessageAttachmentsComponent } from '../message-attachments/message-attachments.component';
import { CopyButtonComponent } from '../copy-button/copy-button.component';

const IMAGE_ONLY_DEFAULT_PROMPT = 'What is in this image?';

@Component({
  selector: 'cb-message-bubble',
  standalone: true,
  imports: [StreamingCursorComponent, MarkdownMessageComponent, MessageAttachmentsComponent, CopyButtonComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isUser()) {
      <div class="cb-flex cb-flex-col cb-items-end cb-gap-1.5 cb-px-0.5">
        @if (hasAttachments()) {
          <cb-message-attachments [parts]="message().parts" variant="user" />
        }
        @if (showUserText()) {
          <div class="cb-user-bubble cb-max-w-[85%]">
            <p class="cb-whitespace-pre-wrap cb-break-words">{{ text() }}</p>
          </div>
        }
        @if (canCopy() && showUserText()) {
          <cb-copy-button [text]="text()" ariaLabel="Copy message" [inline]="true" />
        }
      </div>
    } @else {
      <div [class]="'cb-assistant-message ' + (embedded() ? 'cb-w-full' : 'cb-max-w-full')">
        <div class="cb-assistant-bubble">
          @if (showPlainStream()) {
            <p class="cb-whitespace-pre-wrap cb-text-[13px] cb-leading-[1.55] cb-text-cb-text">
              {{ text() }}<cb-streaming-cursor />
            </p>
          } @else if (showMarkdown()) {
            <cb-markdown-message [content]="text()" />
          } @else {
            <p class="cb-text-[13px] cb-text-cb-muted">…</p>
          }
        </div>
        @if (hasAssistantFiles() && !isStreaming()) {
          <cb-message-attachments [parts]="message().parts" variant="assistant" />
        }
        @if (canCopy()) {
          <div class="cb-message-actions">
            <cb-copy-button [text]="text()" ariaLabel="Copy response" />
          </div>
        }
      </div>
    }
  `,
})
export class MessageBubbleComponent {
  readonly message = input.required<Message>();
  readonly streamingText = input<string | undefined>(undefined);
  readonly isStreaming = input(false);
  readonly embedded = input(false);

  readonly isUser = computed(() => this.message().role === 'user');

  readonly text = computed(() => {
    if (this.isStreaming() && this.streamingText() !== undefined) return this.streamingText()!;
    return getMessageText(this.message());
  });

  readonly showMarkdown = computed(() => !this.isUser() && !this.isStreaming() && this.text().trim().length > 0);
  readonly showPlainStream = computed(() => !this.isUser() && this.isStreaming());
  readonly canCopy = computed(() => !this.isStreaming() && this.text().trim().length > 0);

  readonly hasAttachments = computed(() =>
    this.message().parts.some(p => isImageLikePart(p) || isFilePart(p))
  );
  readonly hasAssistantFiles = computed(() =>
    !this.isUser() && this.message().parts.some(p => isFilePart(p))
  );
  readonly showUserText = computed(() => {
    const t = this.text();
    return Boolean(t) && !(t === IMAGE_ONLY_DEFAULT_PROMPT && this.hasAttachments());
  });
}

// chatbot-react-library/src/components/MessageBubble.tsx
import type { Message } from "../types";
import { IMAGE_ONLY_DEFAULT_PROMPT } from "../utils/attachments";
import { getMessageText, isImageLikePart, isFilePart } from "../utils/messageParts";
import { CopyButton } from "./CopyButton";
import { MarkdownMessage } from "./MarkdownMessage";
import { MessageAttachments } from "./MessageAttachments";
import { StreamingCursor } from "./StreamingCursor";

interface MessageBubbleProps {
  message: Message;
  streamingText?: string;
  isStreaming?: boolean;
  embedded?: boolean;
}

export function MessageBubble({
  message,
  streamingText,
  isStreaming,
  embedded = false,
}: MessageBubbleProps) {
  const isUser = message.role === "user";
  const text =
    isStreaming && streamingText !== undefined
      ? streamingText
      : getMessageText(message);
  const showMarkdown = !isUser && !isStreaming && text.trim().length > 0;
  const showPlainStream = !isUser && isStreaming;
  const canCopy = !isStreaming && text.trim().length > 0;
  const hasAttachments = message.parts.some(
    (p) => isImageLikePart(p) || isFilePart(p),
  );
  const hasAssistantFiles =
    !isUser && message.parts.some((p) => isFilePart(p));
  const showUserText =
    Boolean(text) && !(text === IMAGE_ONLY_DEFAULT_PROMPT && hasAttachments);

  if (isUser) {
    return (
      <div className="cb-flex cb-flex-col cb-items-end cb-gap-1.5 cb-px-0.5">
        {hasAttachments ? (
          <MessageAttachments parts={message.parts} variant="user" />
        ) : null}
        {showUserText ? (
          <div className="cb-user-bubble cb-max-w-[85%]">
            <p className="cb-whitespace-pre-wrap cb-break-words">{text}</p>
          </div>
        ) : null}
        {canCopy && showUserText ? (
          <CopyButton text={text} ariaLabel="Copy message" className="cb-copy-btn--inline" />
        ) : null}
      </div>
    );
  }

  const assistantContent = (
    <div className={`cb-assistant-message ${embedded ? "cb-w-full" : "cb-max-w-full"}`}>
      <div className="cb-assistant-bubble">
        {showPlainStream ? (
          <p className="cb-whitespace-pre-wrap cb-text-[13px] cb-leading-[1.55] cb-text-cb-text">
            {text}
            <StreamingCursor />
          </p>
        ) : showMarkdown ? (
          <MarkdownMessage content={text} />
        ) : (
          <p className="cb-text-[13px] cb-text-cb-muted">…</p>
        )}
      </div>
      {hasAssistantFiles && !isStreaming && (
        <MessageAttachments parts={message.parts} variant="assistant" />
      )}
      {canCopy && (
        <div className="cb-message-actions">
          <CopyButton text={text} ariaLabel="Copy response" />
        </div>
      )}
    </div>
  );

  if (embedded) return assistantContent;

  return <div className="cb-flex cb-justify-start">{assistantContent}</div>;
}
